# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_make_h5_altrep <- function(file_name, dataset_name, type = 0L, transpose = FALSE, attributes = NULL) {
    .Call(`_HighFive_C_make_h5_altrep`, file_name, dataset_name, type, transpose, attributes)
}

C_read_h5_altrep <- function(file_name, dataset_name, offset, length, trans = FALSE, type = 0L) {
    .Call(`_HighFive_C_read_h5_altrep`, file_name, dataset_name, offset, length, trans, type)
}

get_type_index <- function(type_name) {
    .Call(`_HighFive_get_type_index`, type_name)
}

get_dims <- function(file_name, dataset_name) {
    .Call(`_HighFive_get_dims`, file_name, dataset_name)
}

