# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_make_h5_altrep <- function(type, file_name, dataset_name) {
    .Call(`_HighFive_C_make_h5_altrep`, type, file_name, dataset_name)
}

read_h5_vector <- function(type, file_name, dataset_name, offset, length) {
    .Call(`_HighFive_read_h5_vector`, type, file_name, dataset_name, offset, length)
}

C_read_h5_altrep <- function(type, file_name, dataset_name, offset, length, trans = FALSE) {
    .Call(`_HighFive_C_read_h5_altrep`, type, file_name, dataset_name, offset, length, trans)
}

